# Page settings

baseurl = "https://resume.danmanners.com/"
languageCode = "en-us"
title = "Dan Manners' Resume"
theme = "hugo-orbit-theme"
googleAnalytics = "UA-131029076-1"

# Do not build files for websites. Need them? Set to false
disableRSS = true
disableSitemap = true
disable404 = true

[params]

# Meta
    description = "Hugo Responsive Resume/CV Theme for Developers"
    author = "Pavel Kanyshev"

# Theme styles

    # The original template comes with 6 colour schemes. You may choose styles below.
    # "styles.css", "styles-2.css", "styles-3.css", "styles-4.css", "styles-5.css", "styles-6.css"
    # are available. Also the source LESS files are included so
    # it’s quick and easy to change the styling and colour scheme.

    styles = "styles-6.css"

# Sidebar sections

    # Profile section
    [params.profile]
        name = "Dan Manners"
        tagline = "Senior Network Engineer | DevOps Engineer | Solutions Designer"
        avatar = "dan.png"

    # Contact section
    [params.contact]
        enable = true

        [[params.contact.list]]
        class = "email"
        icon = "fa-envelope"
        url = "mailto:daniel.a.manners@gmail.com"
        title = "daniel.a.manners@gmail.com"

        [[params.contact.list]]
        class = "phone"
        icon = "fa-phone"
        url = "tel:+19147155428"
        title = "+19147155428"

        [[params.contact.list]]
        class = "phone"
        icon = "fa-comments"
        url = "sms:+19147155428"
        title = "+19147155428"

        [[params.contact.list]]
        class = "website"
        icon = "fa-globe"
        url = "//danmanners.com"
        title = "danmanners.com"

        [[params.contact.list]]
        class = "linkedin"
        icon = "fa-linkedin"
        url = "//linkedin.com/in/danielmanners"
        title = "linkedin.com/in/danielmanners"

        [[params.contact.list]]
        class = "github"
        icon = "fa-github"
        url = "//github.com/danmanners"
        title = "github.com/danmanners"

    # Education section
    [params.education]
        enable = true
        title = "Education"

        [[params.education.list]]
        college = "Hartford University"
        dates = "2009 - 2010"

    # Languages section
    [params.language]
        enable = true
        title = "Languages"

        [[params.language.list]]
        language = "English"
        level = "Native"

    # Interests section
    [params.interests]
        enable = true
        title = "Interests"

        [[params.interests.list]]
        interest = "Music"
        [[params.interests.list]]
        interest = "Gaming"
        [[params.interests.list]]
        interest = "Learning"
        [[params.interests.list]]
        interest = "Homelabbing"
        [[params.interests.list]]
        interest = "Food & Cooking"
        [[params.interests.list]]
        interest = "Concerts and Live Events"

    # Skills section
    [params.rskill]
        enable = true
        title = "Skills & Proficiency"
        [[params.rskill.list]]
        skill = "On-Prem Networking"
        level = "92%"
        [[params.rskill.list]]
        skill = "Python, Django & Flask"
        level = "68%"
        [[params.rskill.list]]
        skill = "Gitlab/Github/Bitbucket"
        level = "80%"
        [[params.rskill.list]]
        skill = "pfSense"
        level = "95%"
        [[params.rskill.list]]
        skill = "Asterisk VoIP"
        level = "75%"
        [[params.rskill.list]]
        skill = "Linux"
        level = "88%"
        [[params.rskill.list]]
        skill = "Automation Tooling"
        level = "79%"
        [[params.rskill.list]]
        skill = "Docker & Kubernetes"
        level = "73%"
        [[params.rskill.list]]
        skill = "Amazon Web Services"
        level = "88%"
        [[params.rskill.list]]
        skill = "DigitalOcean"
        level = "84%"
        [[params.rskill.list]]
        skill = "Hashicorp Vault"
        level = "77%"
        [[params.rskill.list]]
        skill = "Windows System Administration"
        level = "58%"

# Main body sections
    # You may use markdown in summary, details and intro fields. But don't overdose, it's resume!:)
    # Summary section
    [params.summary]
        enable = true
        icon = "fa-user"
        title = "Career Profile"
        summary = """**With over a decade in the IT industry**, I have been able to use my problem solving abilities, ingenuity, and my knowledge of best-practices to support my clients’ goals and the projects we work on.
        \nI thrive on tackling new challenges and engineering the best solutions. I am well-versed in automation tooling, cloud and on-prem networking, systems architecture, SecOps. Additionally, I am experienced in troubleshooting at the hardware, software, and application levels of most systems put in front of me.
        \nI always aim to develop appropriate solutions for the appropriate time frames and within budget. I am always seeking new opportunities to develop cohesive systems which can provide the ideal environments for both developers and their end users."""

    # Experiences section
    [params.experiences]
        enable = true
        icon = "fa-briefcase"
        title = "Experiences"

        [[params.jobs.list]]
        position = "DevOps Engineer"
        dates = "2020 - Present"
        company = "Cisco"
        details = "Working with the Engineering IT team to design, build and implement a platform to streamline code and package deployment to both internal and zero-trust partner locations."

        [[params.jobs.list]]
        position = "Senior Network Engineer, Systems and Design"
        dates =    "2019 - 2020"
        company =  "TOURtech"
        details =  "Building and implementing better systems for deploying the necessary configurations to different types of devices; Work with the Field Services team to ensure that on-site issues are handled appropriately and in a timely manner; Work on bettering both the customer experience as well as both the on-site and remote administration experience with technology."

        [[params.jobs.list]]
        position = "DevOps Engineer"
        dates =    "2017 - 2019"
        company =  "BrainGu, LLC"
        details =  "Worked collaberatively with developers, project managers, and upper management to guarantee end products and results that both we and our customers love. Primarily worked on the Structsure Project building out the system architecture and automated deployment and updating functionality of the application being built."

        [[params.jobs.list]]
        position = "Network Engineer / Manager of IT Services"
        dates =    "2014 - 2017"
        company =  "TOURtech"
        details =  "Worked with both internal and external teams to guarantee success at the events we built and operated. Helped coordinate 50+ shows during my tenure. Built the \"Tech Wiki\" for configuration and knowledge management."

        [[params.jobs.list]]
        position = "Systems Administrator I/II"
        dates =    "2010 - 2014"
        company =  "Production Resource Group"
        details =  "Played a key role in maintaining day-to-day functionality of all networked services (Asset management platform, Cisco phones, print services, networked storage, facility access control, security system management, day-to-day hardware/software problems, client and project management, etc.) both locally and nationwide."

        [[params.jobs.list]]
        position = "Systems Administrator Intern"
        dates =    "Summer 2009"
        company =  "Production Resource Group"
        details =  "Performed day-to-day helpdesk support for the US; built and applied Active Directory schema changes."

    # Projects section
    [params.projects]
        enable = true
        icon = "fa-archive"
        title = "Projects"

        [[params.projects.list]]
        title = "CAPCOM @ TOURtech"
        url = "https://www.tourtech.com"
        tagline = """Built out a highly scalable platform, primarily around Open Source Software, to allow simultaneous remote management and support to multiple event sites. This includes:
        \n- CCTV Cameras
        \n- Temporary wired and wireless infrastructure
        \n- Logging and Metrics collection
        \n- Integration with on-site radio communications
        \nCAPCOM provides the ability for a less-qualified network technician on multiple event sites while a highly-trained remote Network engineer can oversee simultaneous live events from a single physical location."""

        [[params.projects.list]]
        title = "EventBuilder @ TOURtech"
        url = "https://www.tourtech.com"
        tagline = "Built an easy-to-use web interface to generate TOURtech specific configuration files for the various hardware used by the organization on a per-event basis. This streamlined configuration management by nearly a full day of work per job."

        [[params.projects.list]]
        title = "Structsure @ BrainGu"
        url = "https://www.structsure.com"
        tagline = "Compliant Platform-As-A-Service offering simplifed deployments of necessary applications for almost any business."

        [[params.projects.list]]
        title = "Austin City Limits Music Festival 2015"
        url = "https://www.aclfestival.com/"
        tagline = "Designed the network architecture, deployed, and troubleshot both the production networking and AT&T public Wifi for VIP attendees. Successfully provided internet to 80,000+ wired and wireless clients over two weekends of the music festival including POS, Access Control, CCTV, and attendee wifi."

        [[params.projects.list]]
        title = "PRG Los Angeles Facility Move"
        url = "https://www.prg.com/locations/los-angeles"
        tagline = "Moved from ~80,000sqft warehouse to a ~135,000sqft warehouse; performed a full upgrade of all network infrastructure and upgraded desktop clients for office and warehouse use."

        [[params.projects.list]]
        title = "PRG New Jersey Facility Move"
        url = "https://www.prg.com/locations/secaucus"
        tagline = "Assisted in merging two company locations from Mt. Vernon, NY and North Bergen, NJ into a single facility in Secaucus, NJ. 130+ employees and 90+ workstations migrated, as well as assisting with testing various core systems (Ethernet integrity, paging systems, video security systems)."

    # Location section
    [params.location]
        enable = true
        icon = "fa-globe"
        title = "Locations"

        [[params.location.list]]
        title = "Westchester, NY"
        tagline = "April 2010 - January 2011"

        [[params.location.list]]
        title = "North Bergen, NJ"
        tagline = "January 2011 - June 2012"

        [[params.location.list]]
        title = "Los Angeles, CA"
        tagline = "June 2012 - November 2015"

        [[params.location.list]]
        title = "Raleigh, NC"
        tagline = "November 2015 - Current"

    # Legacy Skills section
    [params.skills]
        enable = false
        icon = "fa-rocket"
        title = "Skills & Proficiency"

        [[params.skills.list]]
        skill = "On-Prem Networking"
        level = "92%"

        [[params.skills.list]]
        skill = "Automation Tooling"
        level = "79%"

        [[params.skills.list]]
        skill = "Docker & Kubernetes"
        # level = "73%"

        [[params.skills.list]]
        skill = "Amazon Web Services"
        level = "88%"

        [[params.skills.list]]
        skill = "DigitalOcean"
        level = "84%"

        [[params.skills.list]]
        skill = "Python, Django & Flask"
        level = "68%"

        [[params.skills.list]]
        skill = "Gitlab/Github/Bitbucket"
        level = "80%"

        [[params.skills.list]]
        skill = "Hashicorp Vault"
        level = "77%"

        [[params.skills.list]]
        skill = "Asterisk VoIP"
        level = "75%"

        [[params.skills.list]]
        skill = "pfSense"
        level = "95%"

        [[params.skills.list]]
        skill = "Linux"
        level = "88%"

        [[params.skills.list]]
        skill = "Windows System Administration"
        level = "58%"

    # Footer section

    # The original template is released under the Creative Commons Attribution 3.0 License.
    # Please keep the original attribution link when using for your own project.
    # If you'd like to use the template without the attribution,
    # you can check out other license options via template author's website: themes.3rdwavemedia.com
    # 
    # As for Hugo port you may rewrite the "Ported for..." line with setting your name below.

    [params.footer]
        copyright = "Ported for Dan Manners"
