# Page settings

baseurl = "https://resume.danmanners.com/"
languageCode = "en-us"
title = "Dan Manners' Resume"
theme = "hugo-orbit-theme"
googleAnalytics = "UA-131029076-1"

# Do not build files for websites. Need them? Set to false
disableRSS = true
disableSitemap = true
disable404 = true

[params]

# Meta
    description = "Hugo Responsive Resume/CV Theme for Developers"
    author = "Pavel Kanyshev"

# Theme styles

    # The original template comes with 6 colour schemes. You may choose styles below.
    # "styles.css", "styles-2.css", "styles-3.css", "styles-4.css", "styles-5.css", "styles-6.css"
    # are available. Also the source LESS files are included so
    # it’s quick and easy to change the styling and colour scheme.

    styles = "styles-6.css"

# Sidebar sections

    # Profile section
    [params.profile]
        name = "Dan Manners"
        tagline = "DevOps Engineer/Architect, Solutions Designer"
        avatar = "dan.png"

    # Contact section
    [params.contact]
        enable = true

        [[params.contact.list]]
        class = "email"
        icon = "fa-envelope"
        url = "mailto:daniel.a.manners@gmail.com"
        title = "daniel.a.manners@gmail.com"

        [[params.contact.list]]
        class = "phone"
        icon = "fa-phone"
        url = "tel:+19147155428"
        title = "+19147155428"

        [[params.contact.list]]
        class = "website"
        icon = "fa-globe"
        url = "//danmanners.com"
        title = "danmanners.com"

        [[params.contact.list]]
        class = "linkedin"
        icon = "fa-linkedin"
        url = "//linkedin.com/in/danielmanners"
        title = "linkedin.com/in/danielmanners"

        [[params.contact.list]]
        class = "github"
        icon = "fa-github"
        url = "//github.com/danmanners"
        title = "github.com/danmanners"

    # Education section
    [params.education]
        enable = true
        title = "Education"

        [[params.education.list]]
        college = "Hartford University"
        dates = "2009 - 2010"

    # Languages section
    [params.language]
        enable = true
        title = "Languages"

        [[params.language.list]]
        language = "English"
        level = "Native"

    # Interests section
    [params.interests]
        enable = true
        title = "Interests"

        [[params.interests.list]]
        interest = "Homelabbing"

        [[params.interests.list]]
        interest = "Food & Cooking"

        [[params.interests.list]]
        interest = "Music"

        [[params.interests.list]]
        interest = "Gaming"

# Main body sections

    # You may use markdown in summary, details and intro fields. But don't overdose, it's resume!:)

    # Summary section
    [params.summary]
        enable = true
        icon = "fa-user"
        title = "Career Profile"
        summary = "**Summarise your career here** lorem ipsum dolor sit amet, consectetuer adipiscing elit. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu."

    # Experiences section
    [params.experiences]
        enable = true
        icon = "fa-briefcase"
        title = "Experiences"

        [[params.jobs.list]]
        position = "DevOps Engineer"
        dates = "2017 - Present"
        company = "BrainGu, LLC"
        details = "**Describe your role here** lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo.\n\n Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo."

        [[params.jobs.list]]
        position = "Senior Network Technician / Manager of IT Services"
        dates = "2014 - 2016"
        company = "TOURtech"
        details = "**Describe your role here** lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem."

        [[params.jobs.list]]
        position = "Systems Administrator I/II"
        dates = "2010 - 2014"
        company = "Production Resource Group"
        details = "**Describe your role here** lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem."

    # Projects section
    [params.projects]
        enable = false
        icon = "fa-archive"
        title = "Projects"
        intro = "**You can list your side projects or open source libraries in this section.** Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum et ligula in nunc bibendum fringilla a eu lectus"

        [[params.projects.list]]
        title = "Simple FAQ Theme for Hugo"
        url = "https://github.com/aerohub/hugo-faq-theme"
        tagline = "Simple FAQ Theme for Hugo. You may use this theme for building very simple FAQs or note lists."

        [[params.projects.list]]
        title = "Hugo Identity"
        url = "https://github.com/aerohub/hugo-identity-theme"
        tagline = "Little profile/card-style template for Hugo."

    # Skills section
    [params.skills]
        enable = true
        icon = "fa-rocket"
        title = "Skills & Proficiency"

        [[params.skills.list]]
        skill = "On-Prem Networking"
        level = "92%"

        [[params.skills.list]]
        skill = "Automation Tooling"
        level = "79%"

        [[params.skills.list]]
        skill = "Docker & Kubernetes"
        level = "73%"

        [[params.skills.list]]
        skill = "Amazon Web Services"
        level = "88%"

        [[params.skills.list]]
        skill = "DigitalOcean"
        level = "84%"

        [[params.skills.list]]
        skill = "Python, Django & Flask"
        level = "68%"

        [[params.skills.list]]
        skill = "Hashicorp Vault"
        level = "80%"

        [[params.skills.list]]
        skill = "Asterisk VoIP"
        level = "80%"

        [[params.skills.list]]
        skill = "Linux"
        level = "88%"

        [[params.skills.list]]
        skill = "Windows System Administration"
        level = "58%"

    # Footer section

    # The original template is released under the Creative Commons Attribution 3.0 License.
    # Please keep the original attribution link when using for your own project.
    # If you'd like to use the template without the attribution,
    # you can check out other license options via template author's website: themes.3rdwavemedia.com
    # 
    # As for Hugo port you may rewrite the "Ported for..." line with setting your name below.

    [params.footer]
        copyright = "Ported for Dan Manners"
